# fly.toml app configuration file generated for sasquatchsports on 2023-07-13T10:38:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sasquatchsports"
primary_region = "dfw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "npm run seed"